project_name: multissh-go
builds:
  - main: ./cmd/multissh/main.go
    binary: multissh
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
brews:
  - name: multissh-go
    tap:
      owner: lcrownover
      name: homebrew-tap
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/lcrownover/multissh-go"
    folder: Formula
    license: "MIT"


